name: Build Plugin

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  gradle-build:
    runs-on: ubuntu-latest
    steps:
      - name: git clone
        uses: actions/checkout@v5
      - name: git clone gradlex-build-conventions
        uses: actions/checkout@v4
        with:
          repository: gradlex-org/plugin-publish-conventions
          path: build/plugin-publish-conventions
          ref: new-convention-plugins
      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          # Java 11 for Gradle 6.x support
          java-version: |
            11
            17
      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v5
      - run: "./gradlew build"