name: Build Plugin

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  gradle-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-java@v5
        with:
          distribution: temurin
          # Java 11 for Gradle 6.x support
          java-version: |
            11
            17
      - uses: gradle/actions/setup-gradle@v6
        with:
          build-scan-terms-of-use-url: https://gradle.com/help/legal-terms-of-use
          build-scan-terms-of-use-agree: yes
      - uses: testlens-app/setup-testlens@v1.9.0
      - run: "./gradlew build"